[general]
import = ["~/.config/alacritty/colors.toml"]

[font]
size = 12
normal = { family = "Hasklug Nerd Font", style = "Regular" }
bold = { family = "Hasklug Nerd Font", style = "Bold" }
italic = { family = "Hasklug Nerd Font", style = "Italic" }
bold_italic = { family = "Hasklug Nerd Font", style = "Bold Italic" }
